FROM tobix/pywine:3.12

RUN mkdir /app
WORKDIR /app

COPY . .

RUN wine python -m pip install --upgrade pip setuptools wheel
RUN wine pip install poetry
RUN wine poetry add pyinstaller

CMD wine poetry install --no-root && wine poetry run python ./pyinstaller.py