FROM python:3.12

RUN mkdir /app
WORKDIR /app

COPY . .

RUN python -m pip install --upgrade pip setuptools wheel
RUN pip install poetry
RUN poetry add pyinstaller

CMD poetry install --no-root && poetry run python pyinstaller.py