name: Build Windows Executable

on:
  push:
    branches:
      - main  # Run when pushing to 'main' branch
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"  # Ensure 64-bit version

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry pyinstaller pillow
          poetry self add  poetry-plugin-export
          poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Install Wine for Windows Cross-Compilation
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine-stable

      - name: Install Windows Python 3.12 via Wine
        run: |
          wget https://www.python.org/ftp/python/3.12.2/python-3.12.2-embed-amd64.zip
          unzip python-3.12.2-embed-amd64.zip -d wine-python
          echo -e '[build-system]\nrequires = ["setuptools", "wheel"]\nbuild-backend = "setuptools.build_meta"' > wine-python/pyvenv.cfg

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with PyInstaller
        run: |
          python pyinstaller.py

      - name: Upload EXE as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/ChemDoE.exe